In [12]:
!pip install python-digits

Looking in indexes: https://pypi.org/simple, https://packagecloud.io/github/git-lfs/pypi/simple
  Created wheel for python-digits: filename=python_digits-2.0-py3-none-any.whl size=7358 sha256=b8e4dc057fd53894f274dceb7a7d4bf2ed01f3a320425060edfe08343c58cb31
  Stored in directory: /home/srinu/.cache/pip/wheels/36/f0/80/e714308b28db739972c0d0aa128a7affa1fb62ad764ab86924
Successfully built python-digits


In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits

In [23]:
digits = load_digits()
cross_val_score(LogisticRegression(max_iter = 4000), digits.data, digits.target)

array([0.925     , 0.87777778, 0.93871866, 0.93593315, 0.89693593])

In [20]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [24]:
cross_val_score(RandomForestClassifier(n_estimators = 40), digits.data, digits.target)

array([0.93055556, 0.89444444, 0.95543175, 0.96657382, 0.91086351])

In [25]:
!pip install imbalanced-learn

Looking in indexes: https://pypi.org/simple, https://packagecloud.io/github/git-lfs/pypi/simple
     |████████████████████████████████| 206 kB 2.7 MB/s eta 0:00:01


In [26]:
from imblearn.over_sampling import RandomOverSampler